


### /merchantInfo/addUpdate
POST {{host}}/backend/merchantInfo/addUpdate
Content-Type: application/json

{
  "merchantInfo": "merchantInfo",
  "accessKey": "accessKey",
  "secretKey": "secretKey",
  "status": "ON"
}

### /merchantInfo/find
GET {{host}}/backend/merchantInfo/find



### /depositeBankCardSetting/addUpdate
POST {{host}}/backend/depositeBankCardSetting/addUpdate
Content-Type: application/json

{
  "bankName": "2",
  "bankCode": "2",
  "cardNo": "3",
  "status": "IN_USE"
}

### /depositeBankCardSetting/find
GET {{host}}/backend/depositeBankCardSetting/find?page=1&size=100




