
### /info
GET {{host}}/info

### /infoOne
GET {{host}}/infoOne


### /backend/depositeMerchant/delete
POST {{host}}/backend/depositeMerchant/delete
Content-Type: application/json

{
  "id": "id"
}

### /backend/depositeMerchant/addUpdate
POST {{host}}/backend/depositeMerchant/addUpdate
Content-Type: application/json

{
  "id": "id",
  "merchantId": "merchantId",
  "transactionId": "transactionId",
  "method": "method",
  "amount": 1234,
  "billAmount": 1234,
  "bankCode": "bankCode",
  "cardNo": "cardNo",
  "depositeBankCode": "depositeBankCode",
  "depositeCardNo": "depositeCardNo",
  "depositeName": "depositeName",
  "depositePhone": "depositePhone",
  "expireTime": "expireTime",
  "expireTimeReal": "expireTimeReal",
  "name": "name",
  "phone": "phone",
  "description": "description",
  "qrCode": "qrCode",
  "status": "status",
  "statusCallback": "statusCallback",
  "transactionTime": "transactionTime",
  "channelFee": 1234,
  "depositeBankStatementId": "depositeBankStatementId",
  "accountHolder": "accountHolder",
  "callbackUrl": "callbackUrl"
}

### /backend/depositeMerchant/find
GET {{host}}/backend/depositeMerchant/find

