
### /depositeMerchant/delete
POST {{host}}/backend/depositeMerchant/delete
Content-Type: application/json

{
  "id": "id"
}

### /login
POST {{host}}/backend/login/login
Content-Type: application/json

{
  "loginName": "yangpu",
  "password": "123456"
}

> {%
    client.global.set("__token", response.body.data.token);
%}






### 3.1. 内部人员录入银行流水信息, 上传截图-OCR
POST {{host}}/backend/upload/uploadOCR?u-auth-for-test-only=12
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="testocr.jpg"
Content-Type: image/png

< ./testocr.jpg
--WebAppBoundary--

>
